Models/View/MyHealth/MyHealthDetailsViewModel.cs
using eDoc.Data.Models;
using System.Collections.Generic;

namespace eDoc.Models.View.MyHealth
{
    public class MyHealthDetailsViewModel
    {
        public MyHealthDetailsViewModel()
        {
            this.AllergiesList = new HashSet<Allergy>();
        }
        public string UserFullName { get; set; }
        public int Age { get; set; }
        public ICollection<Allergy> AllergiesList { get; set; }
        public MyWeight MyWeight{ get; set; }
        public MyBloodPressure MyBloodPressure { get; set; }
    }
}

Models/View/MyHealth/MyHealthHistoryViewModel.cs
using eDoc.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eDoc.Models.View.MyHealth
{
    public class MyHealthHistoryViewModel
    {
        public string UserFullName { get; set; }
        public List<MyWeight> MyWeightList { get; set; }
        public List<MyBloodPressure> MyBloodPressureList { get; set; }
        public List<Allergy> MyAllergiesList { get; set; }
    }
}

Controllers/MyHealthController.cs
using eDoc.Models.View.MyHealth;
using eDoc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace eDoc.Controllers
{
    [Authorize]
    public class MyHealthController : Controller
    {
        private readonly IMyHealthService _healthService;

        public MyHealthController(IMyHealthService healthService)
        {
            this._healthService = healthService;
        }


        public IActionResult Details()
        {
            var myHealth = _healthService.GetMyHealthStats();

            return this.View(myHealth);
        }
        public IActionResult Update()
        {
            var myHealth = _healthService.GetMyHealthStats();

            return this.View(myHealth);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(MyHealthDetailsViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return this.View(input);
            }

            var myWeight = input.MyWeight;
            var myBloodPressure = input.MyBloodPressure;

            await _healthService.UpdateWeight(myWeight);
            await _healthService.UpdateBloodPressure(myBloodPressure);

            return this.RedirectToAction("Details");
        }

        public IActionResult History()
        {
            var userHistory = _healthService.GetMyHistory();

            return this.View(userHistory);
        }

        public IActionResult Remove(string id)
        {
            _healthService.RemoveRecord(id);

            return this.RedirectToAction("History");
        }
    }
}

ViewComponents/ProfilePictureViewComponent.cs
using Dropbox.Api;
using eDoc.Data.Models;
using eDoc.Models.View_Components;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks;

namespace eDoc.ViewComponents
{
    public class ProfilePictureViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IConfiguration _config;
        private readonly DropboxClient _dropBoxClient;

        public ProfilePictureViewComponent(UserManager<ApplicationUser> userManager,
                                        IConfiguration config)
        {
            this.userManager = userManager;
            this._config = config;
            this._dropBoxClient = new DropboxClient(_config.GetConnectionString("DropBoxAccessToken"));
        }
        public async Task<IViewComponentResult> InvokeAsync(string user)
        {
            var userProfile = await userManager.FindByIdAsync(user);
            var profilePicture = new ProfilePictureLinkViewModel
            {
                Link = GetUsersProfilePicture(userProfile)
            };

            return View(profilePicture);
        }

        private string GetUsersProfilePicture(ApplicationUser user)
        {
            string picturePath;

            if (string.IsNullOrEmpty(user.ProfilePicture))
            {
                picturePath = "https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg";
            }
            else
            {
                picturePath = this._dropBoxClient.Files.GetTemporaryLinkAsync(user.ProfilePicture).Result.Link;
            }

            return picturePath;
        }
    }
}

Views/MyHealth/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using eDoc.Data.Models
@inject UserManager<ApplicationUser> userManager
@model eDoc.Models.View.MyHealth.MyHealthDetailsViewModel

        <div class="card text-center" style="width: 18rem;">
            <vc:profile-picture user="@userManager.GetUserId(this.User)" />
            <div class="card-body">
                <h5 class="card-title">@Model.UserFullName</h5>
                <p class="card-text">Възраст: @Model.Age г.</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Тегло: @Model.MyWeight?.Value</li>
                <li class="list-group-item">Кръвно: @Model.MyBloodPressure?.Systolic / @Model.MyBloodPressure?.Diastolic </li>
            </ul>
            <div class="card-body">
                <a asp-controller="MyHealth" asp-action="Update" class="btn btn-outline-info">Промени</a>
            </div>
        </div>

Views/MyHealth/History.cshtml
@using eDoc.Models.View.MyHealth
@model MyHealthHistoryViewModel
@{ int a = 0; int b = 0; }
<h1>История на записите: @Model.UserFullName</h1>

<h2>Моето тегло</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">КГ.</th>
            <th scope="col">Дата</th>
            <th scope="col">Премахни</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var record in Model.MyWeightList)
        {
            <tr>
                <th scope="row">@{a++;} @a</th>
                <td>@record.Value кг.</td>
                <td>@record.RecordDate г.</td>
                <td><a class="btn-outline-danger" asp-controller="MyHealth" asp-action="Remove" asp-route-id="@record.Id">Премахни</a></td>
            </tr>
        }
    </tbody>
</table>

<hr />

<h2>Моето кръвно налягане</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Стойност (систолично/диастолично)</th>
            <th scope="col">Дата</th>
            <th scope="col">Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var record in Model.MyBloodPressureList)
        {
            <tr>
                <th scope="row">@{b++;} @b</th>
                <td>@record.Systolic / @record.Diastolic</td>
                <td>@record.RecordDate г.</td>
                <td><a class="btn-outline-danger" asp-controller="MyHealth" asp-action="Remove" asp-route-id="@record.Id">Премахни</a></td>
            </tr>
        }
    </tbody>
</table>

Views/MyHealth/Update.cshtml
@using Microsoft.AspNetCore.Identity
@using eDoc.Data.Models
@inject UserManager<ApplicationUser> userManager
@model eDoc.Models.View.MyHealth.MyHealthDetailsViewModel

    <div class="mr-4">
        <form method="post" asp-controller="MyHealth" asp-action="Update" class="text-center">
            <div class="card" style="width: 18rem;">
                <vc:profile-picture user="@userManager.GetUserId(this.User)" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">
                    <h5 class="card-title">@Model.UserFullName</h5>
                    <p class="card-text">Възраст: @Model.Age г.</p>
                </div>
                <ul class="list-group list-group-flush">

                    <li class="list-group-item">
                        Тегло: <br />
                        <span asp-validation-for="@Model.MyWeight.Value" class="text-danger"></span>
                        <input asp-for="@Model.MyWeight.Value" /> кг.
                    </li>
                    <li class="list-group-item">
                        Кръвно: <br />
                        <span asp-validation-for="@Model.MyBloodPressure.Systolic" class="text-danger"></span>
                        <input asp-for="@Model.MyBloodPressure.Systolic" />(систолично) <br />
                        <span asp-validation-for="@Model.MyBloodPressure.Diastolic" class="text-danger"></span>
                        <input asp-for="@Model.MyBloodPressure.Diastolic" /> (диастоличното)
                    </li>
                </ul>
                <div class="card-body">
                    <button type="submit" class="btn btn-outline-success">Запази</button>
                </div>
            </div>
        </form>
    </div>