Controllers/DoctorController.cs
using eDoc.Data.Models;
using eDoc.Models.Input;
using eDoc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace eDoc.Controllers
{
    [Authorize]
    [Authorize(Roles = "eDoctor,GodModeAdmin")]
    public class DoctorController : Controller
    {
        private readonly IDoctorService _doctorService;
        private readonly UserManager<ApplicationUser> _userManager;

        public DoctorController(IDoctorService doctorService, 
                                UserManager<ApplicationUser> userManager)
        {
            this._doctorService = doctorService;
            this._userManager = userManager;
        }

        public IActionResult CreateRecipe()
        {
            var recipeModel = _doctorService.PrepareRecipeInputModel();

            return this.View(recipeModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateRecipe(CreateRecipeInputModel input)
        {
            _doctorService.CreateRecipe(input);

            return Redirect("/");
        }

        public IActionResult CreateAmbulatoryList()
        {
            var ambListInputModel = _doctorService.PrepareAmbListInputModel();

            return this.View(ambListInputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateAmbulatoryList(AmbulatoryListInputModel input)
        {
            _doctorService.CreateAmbulatoryList(input);

            return this.Redirect("/");
        }

        public IActionResult CreateSickLeaveList()
        {
            var sickLeaveInputModel = _doctorService.PrepareSickLeaveInputModel();

            return this.View(sickLeaveInputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSickLeaveList(SickLeaveListInputModel input)
        {
            _doctorService.CreateSickLeaveList(input);

            return this.Redirect("/");
        }

        public IActionResult MyPatients()
        {
            var doctorId = _userManager.GetUserAsync(User).GetAwaiter().GetResult().Id;

            var myPatients = _doctorService.GetDoctorPatients(doctorId);

            return this.View(myPatients);
        }

        public IActionResult IssuedRecipes()
        {
            var issuedRecipes = _doctorService.GetRecipesIssueByMe();
            return this.View(issuedRecipes);
        }


        public IActionResult IssuedAmbulatoryLists()
        {
            var issuedLists = _doctorService.GetAmbulatoryListsIssueByMe();
            return this.View(issuedLists);
        }

        public IActionResult IssuedSickLeaveLists()
        {
            var issuedSickLeaves = _doctorService.GetSickLeavesIssueByMe();
            return this.View(issuedSickLeaves);
        }

        public IActionResult RemovePatient(string id)
        {
            this._doctorService.RemovePatient(id);

            return this.RedirectToAction("MyPatients");
        }



    }
}


Controllers/MyHealthController.cs
using eDoc.Models.View.MyHealth;
using eDoc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace eDoc.Controllers
{
    [Authorize]
    public class MyHealthController : Controller
    {
        private readonly IMyHealthService _healthService;

        public MyHealthController(IMyHealthService healthService)
        {
            this._healthService = healthService;
        }


        public IActionResult Details()
        {
            var myHealth = _healthService.GetMyHealthStats();

            return this.View(myHealth);
        }
        public IActionResult Update()
        {
            var myHealth = _healthService.GetMyHealthStats();

            return this.View(myHealth);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(MyHealthDetailsViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return this.View(input);
            }

            var myWeight = input.MyWeight;
            var myBloodPressure = input.MyBloodPressure;

            await _healthService.UpdateWeight(myWeight);
            await _healthService.UpdateBloodPressure(myBloodPressure);

            return this.RedirectToAction("Details");
        }

        public IActionResult History()
        {
            var userHistory = _healthService.GetMyHistory();

            return this.View(userHistory);
        }

        public IActionResult Remove(string id)
        {
            _healthService.RemoveRecord(id);

            return this.RedirectToAction("History");
        }
    }
}

Controllers/PatientController.cs
using eDoc.Data.Models;
using eDoc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace eDoc.Controllers
{
    [Authorize]
    [Authorize]
    public class PatientController : Controller
    {
        private readonly IPatientService service;
        private readonly UserManager<ApplicationUser> userManager;

        public PatientController(IPatientService service, UserManager<ApplicationUser> userManager)
        {
            this.service = service;
            this.userManager = userManager;
        }

        public IActionResult MyRecipes()
        {
            var userId = userManager.GetUserId(this.User);

            var myRecipesList = service.GetMyRecipes(userId);

            return View(myRecipesList);
        }
        public IActionResult RecipeDetails(string id)
        {
            var recipeDetails = service.GetRecipeDetails(id);

            return View(recipeDetails);
        }
        public IActionResult AmbulatoryListDetails(string id)
        {
            var ambulatoryListDetails = service.GetAmbulgatoryListDetails(id);

            return View(ambulatoryListDetails);
        }

        public IActionResult SickLeaveDetails(string id)
        {
            var sickLeave = service.GetSickLeaveDetails(id);

            return View(sickLeave);
        }

        public IActionResult MyAmbulatoryLists()
        {
            var userId = userManager.GetUserId(this.User);

            var myAmbulatoryLists = service.GetMyAmbulatoryLists(userId);

            return View(myAmbulatoryLists);
        }
        public IActionResult MySickLeaveLists()
        {
            var userId = userManager.GetUserId(this.User);

            var mySickLeaveLists = service.GetMySickLeaveLists(userId);

            return View(mySickLeaveLists);
        }

        public IActionResult MyDoctor()
        {
            var myDoctor = service.GetMyDoctor();

            if (myDoctor == null)
            {
                return View("MissingDoctor");
            }

            return this.View(myDoctor);
        }

        public IActionResult ListAllDoctors()
        {

            var doctorsList = service.GetDoctorsLists();

            return this.View(doctorsList);
        }

        public IActionResult RemoveMyDoctor()
        {
            service.RemoveMyDoctor();

            return this.RedirectToAction("MyDoctor");
        }

        public IActionResult AssignDoctor(string doctorId)
        {

            service.AssignDoctor(doctorId);

            return this.RedirectToAction("MyDoctor");
        }
    }
}

Controllers/PharmacistController.cs
using eDoc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace eDoc.Controllers
{
    [Authorize]
    [Authorize(Roles = "ePharmacist,GodModeAdmin")]
    public class PharmacistController : Controller
    {
        private readonly IPharmacistService _pharmacistService;
        private readonly IPatientService _patientService;

        public PharmacistController(IPharmacistService pharmacistService, 
                                    IPatientService patientService)
        {
            this._pharmacistService = pharmacistService;
            this._patientService = patientService;
        }

        public IActionResult MyWorkList()
        {
            var myWorkList = _pharmacistService.GetMyWorkList();
            return this.View(myWorkList);
        }

        public IActionResult Find(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return this.RedirectToAction("MyWorkList");
            }
            var recipeDetails = _patientService.GetRecipeDetails(id);

            return this.View(recipeDetails);
        }

        public async Task<IActionResult> Complete(string id)
        {
            await _pharmacistService.CompleteAsync(id);

            return this.RedirectToAction("MyWorkList");
        }

    }
}

Views/Shared/_Footer.cshtml
<footer class="text-center">
    <div class="mb-2">
        <small>
            © 2020 <i class="fa  fa-medkit"></i> еДок
        </small>
    </div>
</footer>

Views/Shared/_HeaderScripts.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
<link href="~/css/site.css" rel="stylesheet" />

Views/Shared/_Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
    @RenderSection("Header", required: false)
    <title>@ViewData["Title"]</title>
</head>
<body class="container register">
    @RenderBody()

    <partial name="_ValidationScriptsPartial" />
    @RenderSection("Scripts", required: false)

</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<eDoc.Data.Models.ApplicationUser> SignInManager
@inject UserManager<eDoc.Data.Models.ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="bg">
<head>
    <partial name="_HeaderScripts" />
    @RenderSection("Header", required: false)
</head>
<body>
    <div class="page-wrapper chiller-theme toggled">
        <a id="show-sidebar" class="btn btn-sm btn-light" href="#">
            <i class="fas fa-bars"></i>
        </a>
        <partial name="_Navbar" />
        <main class="page-content">
            @RenderBody()
            <partial name="_Footer" />
        </main>
    </div>
    @RenderSection("Scripts", required: false)
    <partial name="_LayoutScriptsPartial" />
</body>
</html>

Views/Shared/_LayoutScriptsPartial.cshtml
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="~/Identity/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/Identity/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script src="~/js/sidebar.js"></script>

Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity
@using eDoc.Data.Models
@inject UserManager<ApplicationUser> userManager

<nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
        <div class="sidebar-brand">
            <a asp-controller="Home" asp-action="Index">еДок</a>
            <div id="close-sidebar">
                <i class="fas fa-times"></i>
            </div>
        </div>
        <vc:user-profile user="@userManager.GetUserId(this.User)" />
        <!-- sidebar-header  -->
        @*<div class="sidebar-search">
            <div>
                <div class="input-group">
                    <input type="text" class="form-control search-menu" placeholder="Търся...">
                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div>*@
        <!-- sidebar-search  -->
        <div class="sidebar-menu">
            <ul>
                <li class="header-menu">
                    <span>Моето меню</span>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fas fa-heartbeat"></i>
                        <span>Моето здраве</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a asp-controller="MyHealth" asp-action="Update">
                                    Добави запис
                                </a>
                            </li>
                            <li>
                                <a asp-controller="MyHealth" asp-action="Details">Преглед</a>
                            </li>
                            <li>
                                <a asp-controller="MyHealth" asp-action="History">История на записите</a>
                            </li>
                            <li>
                                <a asp-controller="Patient" asp-action="MyDoctor">Личен лекар</a>
                            </li>
                        </ul>
                    </div>
                </li>
                @if (User.IsInRole("eDoctor"))
                {
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fas fa-hospital-user"></i>
                            <span>Моите пациенти</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                                <li>
                                    <a asp-controller="Doctor" asp-action="MyPatients">Списък пациенти</a>
                                </li>
                                <li>
                                    <a asp-controller="Doctor" asp-action="CreateRecipe">Нова рецепта</a>
                                </li>
                                <li>
                                    <a asp-controller="Doctor" asp-action="CreateAmbulatoryList">Нов амбулаторен лист</a>
                                </li>
                                <li>
                                    <a asp-controller="Doctor" asp-action="CreateSickLeaveList">Нов болничен лист</a>
                                </li>
                                <li>
                                    <a asp-controller="Doctor" asp-action="IssuedRecipes">Издадени рецепти</a>
                                </li>
                                <li>
                                    <a asp-controller="Doctor" asp-action="IssuedAmbulatoryLists">Издадени амбулаторни листове</a>
                                </li>
                                <li>
                                    <a asp-controller="Doctor" asp-action="IssuedSickLeaveLists">Издадени болнични</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                }
                @if (User.IsInRole("ePharmacist"))
                {
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fas fa-prescription-bottle-alt"></i>
                            <span>Фармацевт</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                                <li>
                                    <a asp-controller="Pharmacist" asp-action="MyWorkList">Списък с рецепти</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                }
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="far fa-folder-open"></i>
                        <span>Моите документи</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a asp-controller="Patient" asp-action="MyRecipes">Рецепти</a>
                            </li>
                            <li>
                                <a asp-controller="Patient" asp-action="MyAmbulatoryLists">Амбулаторни листове</a>
                            </li>
                            <li>
                                <a asp-controller="Patient" asp-action="MySickLeaveLists">Болнични листове</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <i class="fas fa-map-marked-alt"></i>
                        <span>Карти</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a asp-controller="Home" asp-action="HospitalsNearMe">Близо до мен</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="header-menu">
                    <span>Бързи връзки</span>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="Index">
                        <i class="fas fa-link"></i>
                        <span>Начало</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Patient" asp-action="MyRecipes">
                        <i class="fas fa-link"></i>
                        <span>Моите рецепти</span>
                    </a>
                </li>
                <li>
                    <a asp-area="Identity" asp-page="/Account/Manage/Index">
                        <i class="fas fa-link"></i>
                        <span>Моят профил</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Patient" asp-action="MyDoctor">
                        <i class="fas fa-link"></i>
                        <span>Моят личен лекар</span>
                    </a>
                </li>
                @*<li>
                    <a asp-controller="Home" asp-action="ContactUs">
                        <i class="fas fa-link"></i>
                        <span>Връзка с нас</span>
                    </a>
                </li>*@
            </ul>
        </div>
        <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
        @*<a href="#">
                <i class="fa fa-bell"></i>
                <span class="badge badge-pill badge-warning notification">3</span>
            </a>
            <a href="#">
                <i class="fa fa-envelope"></i>
                <span class="badge badge-pill badge-success notification">7</span>
            </a>
            <a href="#">
                <i class="fa fa-cog"></i>
                <span class="badge-sonar"></span>
            </a>*@
        <a asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <i class="fas fa-power-off"> Изход</i>
        </a>
    </div>
</nav>